<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Lokasi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->authclass->check_isvalidated(base_url());
        $this->load->model('Lokasi_model');
        $this->load->library('form_validation');        
	   $this->load->library('datatables');
    }

    public function index()
    {
        $data = array('title' => 'lokasi');
        $this->template->load('template','admin/lokasi/lokasi_list', $data);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Lokasi_model->json();
    }

    public function read($id) 
    {
        $row = $this->Lokasi_model->get_by_id($id);
        if ($row) {
            $data = array(
                'title' => 'Read',
		'id_lokasi' => $row->id_lokasi,
		'lokasi' => $row->lokasi,
	    );
            $this->template->load('template','admin/lokasi/lokasi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/lokasi'));
        }
    }

    public function create() 
    {
        $data = array(
            'title' => 'Create',
            'button' => 'Create',
            'action' => site_url('admin/lokasi/create_action'),
	    'id_lokasi' => set_value('id_lokasi'),
	    'lokasi' => set_value('lokasi'),
	);
        $this->template->load('template','admin/lokasi/lokasi_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'lokasi' => $this->input->post('lokasi',TRUE),
	    );

            $this->Lokasi_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/lokasi'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Lokasi_model->get_by_id($id);

        if ($row) {
            $data = array(
                'title' => 'Update',
                'button' => 'Update',
                'action' => site_url('admin/lokasi/update_action'),
		'id_lokasi' => set_value('id_lokasi', $row->id_lokasi),
		'lokasi' => set_value('lokasi', $row->lokasi),
	    );
            $this->template->load('template','admin/lokasi/lokasi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/lokasi'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_lokasi', TRUE));
        } else {
            $data = array(
		'lokasi' => $this->input->post('lokasi',TRUE),
	    );

            $this->Lokasi_model->update($this->input->post('id_lokasi', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/lokasi'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Lokasi_model->get_by_id($id);

        if ($row) {
            $this->Lokasi_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/lokasi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/lokasi'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('lokasi', 'lokasi', 'trim|required');

	$this->form_validation->set_rules('id_lokasi', 'id_lokasi', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Lokasi.php */
/* Location: ./application/controllers/Lokasi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-28 23:49:23 */
/* http://harviacode.com */